name: 'Calculate version'
description: 'Calculates full semantic version using GitVersion tool and base version from Porter manifest file'
inputs:
  manifest_path:
    description: 'Path to the Porter manifest file'
    required: true
  branch:
    description: 'Current branch'
    required: true
outputs:
  version: 
    description: 'The full semantic version number, made safe for docker tag'
runs:
  using: 'node12'
  main: 'dist/index.js'