name: 'Build Porter bundle'
description: 'Builds the Porter bundle'
inputs:
  bundle_dir:
    description: 'Directory containing the bundle'
    required: true
  invocation_image:
    description: 'Name of the invocation image'
    required: true
outputs:
  invocation_image_tag: 
    description: 'The tag from the invocation image'
runs:
  using: 'node12'
  main: 'dist/index.js'