name: 'Build Porter bundle'
description: 'Builds the Porter bundle'
inputs:
  porter_path:
    description: 'Path to the Porter tool'
    required: true
  bundle_dir:
    description: 'Directory containing the bundle'
    required: true
  invocation_image:
    description: 'Name of the invocation image'
    required: true
outputs:
  invocation_image_tag: 
    description: 'The tag from the invocation image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.porter_path }}
    - ${{ inputs.bundle_dir }}
    - ${{ inputs.invocation_image }}