name: 'Publish Porter bundle'
description: 'Publishes the Porter bundle'
inputs:
  bundle_dir:
    description: 'Directory containing the bundle'
    required: true
outputs:
  invocation_image_tag: 
    description: 'The tag from the invocation image'
runs:
  using: 'node12'
  main: 'dist/index.js'