name: 'Detect quickstart solution changes'
description: 'Looks at the set of changes in the commit or PR, and determines whether they are valid, whether a build is required, and if so, for which quickstart solution'
inputs:
  repo_name:
    required: false 
    default: ${{ github.repository }}
  pr_number: 
    required: false
    default: ${{ github.event.number }}
  source_version: 
    required: false
    default: ${{ github.sha }}
outputs:
  changes_are_valid: 
    description: 'Boolean flag which shows whether the set of changes in the commit or PR are valid'
  build_required: 
    description: 'Boolean flag which shows whether a build is required for the set of changes'
  quickstart_solution_path:
    description: 'Path to the quickstart solution that has been modified/added'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_name }}
    - ${{ inputs.pr_number }}
    - ${{ inputs.source_version }}