name: 'Install Porter'
description: 'Installs Porter on the agent'
inputs:
  porter_url:
    description: 'URL for Porter installation file'
    required: false
    default: 'https://cdn.deislabs.io/porter'
  porter_version:
    description: 'Version of Porter to install'
    required: false
    default: 'latest'
  feed_url:
    description: 'Feed URL for mixins'
    required: false
    default: 'https://cdn.deislabs.io/porter/atom.xml'
  mixins:
    description: 'Comma separated list of mixins to install'
    required: false
    default: 'exec,kubernetes,helm,azure'
  mixins_version:
    description: 'Version of mixins to install'
    required: false
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'